SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.price * bs.SALES) AS TOTAL_SALES
FROM BOOK b
JOIN BOOK_SALES bs ON bs.BOOK_ID = b.BOOK_ID
JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE SALES_DATE BETWEEN DATE '2022-01-01' AND DATE '2022-01-31'
GROUP BY a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY
ORDER BY a.AUTHOR_ID ASC, b.CATEGORY DESC;