SELECT rnk_window.MEMBER_NAME, re.REVIEW_TEXT, TO_CHAR(re.REVIEW_DATE, 'YYYY-MM-DD') as REVIEW_DATE
FROM REST_REVIEW re
JOIN 
    (SELECT * 
    FROM (
    SELECT m.MEMBER_ID, m.MEMBER_NAME, COUNT(r.REVIEW_ID) AS review_count,
               RANK() OVER (ORDER BY COUNT(r.REVIEW_ID) DESC) AS rnk
        FROM MEMBER_PROFILE m
        JOIN REST_REVIEW r ON m.MEMBER_ID = r.MEMBER_ID
        GROUP BY m.MEMBER_ID, m.MEMBER_NAME)
    WHERE rnk = 1) rnk_window 
    ON re.MEMBER_ID = rnk_window.MEMBER_ID
    ORDER BY re.REVIEW_DATE ASC, re.REVIEW_TEXT ASC;