SELECT MCDP_CD as "진료과코드", COUNT(*) as "5월예약건수"
FROM APPOINTMENT
WHERE APNT_YMD BETWEEN TO_TIMESTAMP('2022-05-01', 'YYYY-MM-DD HH24:MI:SS') AND TO_TIMESTAMP('2022-05-31', 'YYYY-MM-DD HH24:MI:SS')
GROUP BY MCDP_CD
ORDER BY "5월예약건수" ASC, MCDP_CD ASC;