SELECT f.ID, fn.FISH_NAME, f.LENGTH
FROM FISH_NAME_INFO fn
JOIN (SELECT ID, FISH_TYPE, LENGTH
      FROM FISH_INFO
      WHERE (FISH_TYPE, LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH) FROM FISH_INFO GROUP BY FISH_TYPE)) f
      ON fn.FISH_TYPE = f.FISH_TYPE
ORDER BY ID ASC;
