SELECT f.CATEGORY, f.PRICE AS MAX_PRICE, f.PRODUCT_NAME
FROM FOOD_PRODUCT f
JOIN (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
      FROM FOOD_PRODUCT
      WHERE CATEGORY IN ('식용유', '과자', '국', '김치') 
      GROUP BY CATEGORY) fp ON fp.CATEGORY = f.CATEGORY AND f.PRICE = fp.MAX_PRICE
WHERE f.CATEGORY IN ('식용유', '과자', '국', '김치') 
ORDER BY f.PRICE DESC;